require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  #対象外を指定
  Exclude:
    - bin/*
    - db/**/*
    - log/*
    - tmp/*
    - public/**/*
    - node_modules/**/*
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/*
