version: "3"
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pg_data:
    driver: local
